EcommercePricing-v1:
  n_envs: 8
  n_timesteps: 500000.0
  policy: 'MlpPolicy'
  learning_rate: !!float 7e-4
  n_steps: 5
  gamma: 0.99
  gae_lambda: 1.0
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  rms_prop_eps: 1e-5
  use_rms_prop: true
  normalize_advantage: false
  tensorboard_log: './logs/tensorboard/'
  policy_kwargs:
    net_arch:
      - dict(pi=[64, 64], vf=[64, 64])
    activation_fn: 'tanh'
  verbose: 1