EcommercePricing-v1:
  n_envs: 1
  n_timesteps: 500000.0
  policy: 'MlpPolicy'
  learning_rate: !!float 1e-4
  buffer_size: 100000
  learning_starts: 5000
  batch_size: 32
  tau: 1.0
  gamma: 0.99
  train_freq: 4
  gradient_steps: 1
  target_update_interval: 1000
  exploration_fraction: 0.2
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.05
  max_grad_norm: 10
  tensorboard_log: './logs/tensorboard/'
  policy_kwargs:
    net_arch: [256, 256]
    activation_fn: 'relu'
  verbose: 1