EcommercePricing-v1:
  n_envs: 8
  n_timesteps: 1000000.0
  policy: 'MlpPolicy'
  n_steps: 2048
  batch_size: 64
  gae_lambda: 0.95
  gamma: 0.99
  n_epochs: 10
  ent_coef: 0.01
  learning_rate: !!float 2.5e-4
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  target_kl: null
  tensorboard_log: './logs/tensorboard/'
  policy_kwargs:
    net_arch:
      - dict(pi=[256, 256], vf=[256, 256])
    activation_fn: 'tanh'
  verbose: 1